import image1 from './assests/1.webp'
import image2 from './assests/2.jpg'
import image3 from './assests/3.jpeg'
import image4 from './assests/04.jpg'
import image5 from './assests/05.jpg'
import image6 from './assests/06.jpg'

export const carsData = [{
    id: "1",
    Make: "Audi",
    Model_Year: "2009 Audi A3",
    Plate: "CIL-184",
    Classifications: "Automatic ",
    Year: 2009,
    Color: "Black",
    Price: 80000,
    img: image1,
    average: "6.1km / 1-litre",
  },
  {
    id: "2",
    Make: "Porsche",
    Model_Year: "911",
    Plate: "SKI-167",
    Classifications: "Automatic ",
    Year: 2019,
    Color: "Silver",
    Price: 135000,
    img: image3,
    average: "6.1km / 1-litre",
},
  {
    id: "3",
    Make: "Nissan",
    Model_Year: "GT-R",
    Plate: "KGB-345",
    Classifications: "Automatic ",
    Year: 2016,
    Color: "BlUE",
    Price: 70000,
    img: image4,
    average: "6.1km / 1-litre",
  },
  {
    id: "4",
    Make: "BMW",
    Model_Year: "M3",
    Plate: "CDG-876",
    Classifications: "Automatic ",
    Year: 2010,
    Color: "Black",
    Price: 60500,
    img: image5,
    average: "6.1km / 1-litre",
  },
  {
    id: "5",
    Make: "Audi",
    Model_Year: "S5",
    Plate: "YTR-765",
    Classifications: "Automatic ",
    Year: 2009,
    Color: "Red",
    Price: 53000,
    img: image1,
    average: "6.1km / 1-litre",
  },
  {
    id: "6",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image3,
    average: "6.1km / 1-litre",
  },
  {
    id: "7",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image1,
    average: "6.1km / 1-litre",
  },
  {
    id: "8",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image2,
    average: "6.1km / 1-litre",
  },
  {
    id: "9",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image3,
    average: "6.1km / 1-litre",
  },
  {
    id: "10",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image4,
    average: "6.1km / 1-litre",
  },
  {
    id: "11",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image4,
    average: "6.1km / 1-litre",
  },
  {
    id: "12",
    Make: "Audi",
    Model_Year: "2009 Audi A3",
    Plate: "CIL-184",
    Classifications: "Automatic ",
    Year: 2009,
    Color: "Black",
    Price: 80000,
    img: image1,
    average: "6.1km / 1-litre",
  },
  {
    id: "13",
    Make: "Porsche",
    Model_Year: "911",
    Plate: "SKI-167",
    Classifications: "Automatic ",
    Year: 2019,
    Color: "Silver",
    Price: 135000,
    img: image3,
    average: "6.1km / 1-litre",
},
  {
    id: "14",
    Make: "Nissan",
    Model_Year: "GT-R",
    Plate: "KGB-345",
    Classifications: "Automatic ",
    Year: 2016,
    Color: "BlUE",
    Price: 70000,
    img: image4,
    average: "6.1km / 1-litre",
  },
  {
    id: "15",
    Make: "BMW",
    Model_Year: "M3",
    Plate: "CDG-876",
    Classifications: "Automatic ",
    Year: 2010,
    Color: "Black",
    Price: 60500,
    img: image5,
    average: "6.1km / 1-litre",
  },
  {
    id: "16",
    Make: "Audi",
    Model_Year: "S5",
    Plate: "YTR-765",
    Classifications: "Automatic ",
    Year: 2009,
    Color: "Red",
    Price: 53000,
    img: image1,
    average: "6.1km / 1-litre",
  },
  {
    id: "17",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image3,
    average: "6.1km / 1-litre",
  },
  {
    id: "18",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image1,
    average: "6.1km / 1-litre",
  },
  {
    id: "19",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image2,
    average: "6.1km / 1-litre",
  },
  {
    id: "20",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image3,
    average: "6.1km / 1-litre",
  },
  {
    id: "10",
    Make: "Audi",
    Model_Year: "TT",
    Plate: "MAS-007",
    Classifications: "Automatic ",
    Year: 2008,
    Color: "White",
    Price: 40000,
    img: image4,
    average: "6.1km / 1-litre",
  },
]